-- Create triggers for sequence IDs since some older Oracle versions might not support IDENTITY columns directly for auto-increment.
-- Using GENERATED ALWAYS AS IDENTITY where possible (Oracle 12c+). If using an older Oracle version, we'll need SEQUENCE and TRIGGER.
-- Assuming modern Oracle Database (12c or newer)

-- Drop existing tables to ensure clean setup
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE STUDENT_ANSWERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TEST_ATTEMPTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TEST_QUESTIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TESTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE QUESTIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SUBJECTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOGS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 1. Users Table
CREATE TABLE USERS (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    full_name VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) CHECK (role IN ('Admin', 'Instructor', 'TA', 'Student')) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Audit Logs
CREATE TABLE AUDIT_LOGS (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES USERS(user_id) ON DELETE CASCADE,
    action VARCHAR2(255) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Subjects Table
CREATE TABLE SUBJECTS (
    subject_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE NOT NULL,
    description VARCHAR2(500)
);

-- 4. Questions Bank Table
CREATE TABLE QUESTIONS (
    question_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id NUMBER REFERENCES SUBJECTS(subject_id) ON DELETE CASCADE,
    instructor_id NUMBER REFERENCES USERS(user_id) ON DELETE SET NULL,
    text CLOB NOT NULL,
    option_a VARCHAR2(500) NOT NULL,
    option_b VARCHAR2(500) NOT NULL,
    option_c VARCHAR2(500) NOT NULL,
    option_d VARCHAR2(500) NOT NULL,
    correct_option CHAR(1) CHECK (correct_option IN ('A', 'B', 'C', 'D')) NOT NULL,
    status VARCHAR2(20) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved'))
);

-- 5. Tests Table
CREATE TABLE TESTS (
    test_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id NUMBER REFERENCES USERS(user_id) ON DELETE CASCADE,
    subject_id NUMBER REFERENCES SUBJECTS(subject_id) ON DELETE SET NULL,
    title VARCHAR2(100) NOT NULL,
    duration_minutes NUMBER NOT NULL,
    start_time TIMESTAMP, -- optional, if null test can be taken anytime
    end_time TIMESTAMP,   -- optional, deadline for taking the test
    is_active NUMBER(1) DEFAULT 0 CHECK (is_active IN (0, 1))
);

-- 6. Test Questions Mapping Table
CREATE TABLE TEST_QUESTIONS (
    test_id NUMBER REFERENCES TESTS(test_id) ON DELETE CASCADE,
    question_id NUMBER REFERENCES QUESTIONS(question_id) ON DELETE CASCADE,
    points NUMBER DEFAULT 1,
    PRIMARY KEY (test_id, question_id)
);

-- 7. Test Attempts Table
CREATE TABLE TEST_ATTEMPTS (
    attempt_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id NUMBER REFERENCES TESTS(test_id) ON DELETE CASCADE,
    student_id NUMBER REFERENCES USERS(user_id) ON DELETE CASCADE,
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    score NUMBER(5, 2) DEFAULT 0,
    max_score NUMBER(5, 2) DEFAULT 0
);

-- 8. Student Answers Table
CREATE TABLE STUDENT_ANSWERS (
    attempt_id NUMBER REFERENCES TEST_ATTEMPTS(attempt_id) ON DELETE CASCADE,
    question_id NUMBER REFERENCES QUESTIONS(question_id) ON DELETE CASCADE,
    selected_option CHAR(1) CHECK (selected_option IN ('A', 'B', 'C', 'D')) NOT NULL,
    is_correct NUMBER(1) CHECK (is_correct IN (0, 1)) NOT NULL,
    PRIMARY KEY (attempt_id, question_id)
);

-- =============================================
-- SEED DATA (Default Accounts & Subjects)
-- =============================================
INSERT INTO USERS (username, password_hash, full_name, role, email) VALUES ('admin', '123', 'System Admin', 'Admin', 'admin@mcq.com');
INSERT INTO USERS (username, password_hash, full_name, role, email) VALUES ('teacher', '123', 'Default Teacher', 'Instructor', 'teacher@test.com');
INSERT INTO USERS (username, password_hash, full_name, role, email) VALUES ('student', '123', 'Default Student', 'Student', 'student@test.com');

INSERT INTO SUBJECTS (name, description) VALUES ('Mathematics', 'Core mathematical concepts');
INSERT INTO SUBJECTS (name, description) VALUES ('Physics', 'Fundamental laws of nature');
INSERT INTO SUBJECTS (name, description) VALUES ('Chemistry', 'Structure and properties of matter');
INSERT INTO SUBJECTS (name, description) VALUES ('Biology', 'Study of living organisms');
INSERT INTO SUBJECTS (name, description) VALUES ('Computer Science', 'Programming and algorithms');

--procedures
-- Register User
CREATE OR REPLACE PROCEDURE sp_register_user (
    p_username      IN USERS.username%TYPE,
    p_password_hash IN USERS.password_hash%TYPE,
    p_full_name     IN USERS.full_name%TYPE,
    p_role          IN USERS.role%TYPE,
    p_email         IN USERS.email%TYPE
) AS
BEGIN
    INSERT INTO USERS (username, password_hash, full_name, role, email)
    VALUES (p_username, p_password_hash, p_full_name, p_role, p_email);
END;
/

-- Create Test and return test_id
CREATE OR REPLACE PROCEDURE sp_create_test (
    p_creator_id       IN TESTS.creator_id%TYPE,
    p_subject_id       IN TESTS.subject_id%TYPE,
    p_title            IN TESTS.title%TYPE,
    p_duration_minutes IN TESTS.duration_minutes%TYPE,
    p_test_id          OUT TESTS.test_id%TYPE
) AS
BEGIN
    INSERT INTO TESTS (creator_id, subject_id, title, duration_minutes, is_active)
    VALUES (p_creator_id, p_subject_id, p_title, p_duration_minutes, 0)
    RETURNING test_id INTO p_test_id;
END;
/

-- Create Question and add to Test
CREATE OR REPLACE PROCEDURE sp_create_question_and_add (
    p_subject_id      IN QUESTIONS.subject_id%TYPE,
    p_instructor_id   IN QUESTIONS.instructor_id%TYPE,
    p_text            IN QUESTIONS.text%TYPE,
    p_option_a        IN QUESTIONS.option_a%TYPE,
    p_option_b        IN QUESTIONS.option_b%TYPE,
    p_option_c        IN QUESTIONS.option_c%TYPE,
    p_option_d        IN QUESTIONS.option_d%TYPE,
    p_correct_option  IN QUESTIONS.correct_option%TYPE,
    p_test_id         IN TEST_QUESTIONS.test_id%TYPE
) AS
    v_question_id QUESTIONS.question_id%TYPE;
BEGIN
    INSERT INTO QUESTIONS (
        subject_id, instructor_id, text,
        option_a, option_b, option_c, option_d,
        correct_option, status
    )
    VALUES (
        p_subject_id, p_instructor_id, p_text,
        p_option_a, p_option_b, p_option_c, p_option_d,
        UPPER(p_correct_option), 'Approved'
    )
    RETURNING question_id INTO v_question_id;

    INSERT INTO TEST_QUESTIONS (test_id, question_id, points)
    VALUES (p_test_id, v_question_id, 1);
END;
/

-- Create Test Attempt
CREATE OR REPLACE PROCEDURE sp_create_test_attempt (
    p_test_id     IN TEST_ATTEMPTS.test_id%TYPE,
    p_student_id  IN TEST_ATTEMPTS.student_id%TYPE,
    p_max_score   IN TEST_ATTEMPTS.max_score%TYPE,
    p_attempt_id  OUT TEST_ATTEMPTS.attempt_id%TYPE
) AS
BEGIN
    INSERT INTO TEST_ATTEMPTS (test_id, student_id, score, max_score)
    VALUES (p_test_id, p_student_id, 0, p_max_score)
    RETURNING attempt_id INTO p_attempt_id;
END;
/

-- Update Final Score
CREATE OR REPLACE PROCEDURE sp_update_test_score (
    p_attempt_id IN TEST_ATTEMPTS.attempt_id%TYPE,
    p_score      IN TEST_ATTEMPTS.score%TYPE
) AS
BEGIN
    UPDATE TEST_ATTEMPTS
    SET score = p_score
    WHERE attempt_id = p_attempt_id;
END;
/

--triggers
-- Audit user registration
CREATE OR REPLACE TRIGGER trg_audit_user_insert
AFTER INSERT ON USERS
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOGS (user_id, action)
    VALUES (:NEW.user_id, 'User registered');
END;
/

-- Audit user deletion
CREATE OR REPLACE TRIGGER trg_audit_user_delete
AFTER DELETE ON USERS
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOGS (user_id, action)
    VALUES (:OLD.user_id, 'User deleted');
END;
/

-- Audit test completion
CREATE OR REPLACE TRIGGER trg_audit_test_attempt
AFTER INSERT OR UPDATE OF score ON TEST_ATTEMPTS
FOR EACH ROW
WHEN (NEW.score IS NOT NULL)
BEGIN
    INSERT INTO AUDIT_LOGS (user_id, action)
    VALUES (
        :NEW.student_id,
        'Completed test ' || :NEW.test_id ||
        ' with score ' || :NEW.score || '/' || :NEW.max_score
    );
END;
/

commit;