-- Create triggers for sequence IDs since some older Oracle versions might not support IDENTITY columns directly for auto-increment.
-- Using GENERATED ALWAYS AS IDENTITY where possible (Oracle 12c+). If using an older Oracle version, we'll need SEQUENCE and TRIGGER.
-- Assuming modern Oracle Database (12c or newer)

-- Drop existing tables to ensure clean setup
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TEST_ATTEMPTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TEST_QUESTIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TESTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE QUESTIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 1. Users Table
CREATE TABLE USERS (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    full_name VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) CHECK (role IN ('Admin', 'Instructor', 'TA', 'Student')) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Questions Bank Table
CREATE TABLE QUESTIONS (
    question_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id NUMBER REFERENCES USERS(user_id) ON DELETE SET NULL,
    text CLOB NOT NULL,
    option_a VARCHAR2(500) NOT NULL,
    option_b VARCHAR2(500) NOT NULL,
    option_c VARCHAR2(500) NOT NULL,
    option_d VARCHAR2(500) NOT NULL,
    correct_option CHAR(1) CHECK (correct_option IN ('A', 'B', 'C', 'D')) NOT NULL,
    difficulty VARCHAR2(10) CHECK (difficulty IN ('Easy', 'Medium', 'Hard')),
    status VARCHAR2(20) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved'))
);

-- 3. Tests Table
CREATE TABLE TESTS (
    test_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id NUMBER REFERENCES USERS(user_id) ON DELETE CASCADE,
    title VARCHAR2(100) NOT NULL,
    duration_minutes NUMBER NOT NULL,
    start_time TIMESTAMP, -- optional, if null test can be taken anytime
    end_time TIMESTAMP,   -- optional, deadline for taking the test
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1))
);

-- 4. Test Questions Mapping Table
CREATE TABLE TEST_QUESTIONS (
    test_id NUMBER REFERENCES TESTS(test_id) ON DELETE CASCADE,
    question_id NUMBER REFERENCES QUESTIONS(question_id) ON DELETE CASCADE,
    points NUMBER DEFAULT 1,
    PRIMARY KEY (test_id, question_id)
);

-- 5. Test Attempts Table
CREATE TABLE TEST_ATTEMPTS (
    attempt_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id NUMBER REFERENCES TESTS(test_id) ON DELETE CASCADE,
    student_id NUMBER REFERENCES USERS(user_id) ON DELETE CASCADE,
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    score NUMBER(5, 2) DEFAULT 0,
    max_score NUMBER(5, 2) DEFAULT 0
);

-- Insert Dummy Data
-- Seed Users (Password is 'password' for all, hashed with simple dummy or we assume flask app handles hashing - for ease here we will insert raw or assume a predefined hash)
-- Since we use werkzeug.security in Flask, let's insert clear text passwords and we'll check it differently or we can just leave it to be registered via UI. Let's create an Admin.
-- password = pbkdf2:sha256:600000$somesalt$hash... Wait, let's just create raw admin user and handle it in the python app.
-- To keep it simple, we will just create them from the UI, but let's insert one Admin directly.
-- In reality, password hashing makes inserting RAW seeds hard without knowing the generic hash. Let's rely on the Flask app to create users.

COMMIT;
